pipeline {
    agent any

    environment {
        DOCKER_IMAGE = "dhanamjeevig91@gmail.com"
        CONTAINER_NAME = "node-container"
    }

    stages {

        stage('Clone Code') {
    steps {
        git credentialsId: 'github-creds',
            url: 'https://github.com/mokshith-gnaguraju/pushpitsteels.git',
            branch: 'main'
    }
}

        stage('Build Docker Image') {
            steps {
                bat 'docker build -t %DOCKER_IMAGE% .'
            }
        }

        stage('Push to Docker Hub') {
            steps {
                withCredentials([usernamePassword(
                    credentialsId: 'dockerhub-creds',
                    usernameVariable: 'dhanamjeevi1989',
                    passwordVariable: 'Mokshith@21'
                )]) {
                    bat '''
                    echo %PASSWORD% | docker login -u %USERNAME% --password-stdin
                    docker push %DOCKER_IMAGE%
                    '''
                }
            }
        }

        stage('Deploy Container') {
            steps {
                bat '''
                docker stop %CONTAINER_NAME% || exit 0
                docker rm %CONTAINER_NAME% || exit 0
                docker run -d -p 3000:3000 --name %CONTAINER_NAME% %DOCKER_IMAGE%
                '''
            }
        }
    }
}